# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /misc/linux/rhel6/x86_64/local/bin/cmake

# The command to remove a file.
RM = /misc/linux/rhel6/x86_64/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /misc/linux/rhel6/x86_64/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rjs454/workspace/no_tipping

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rjs454/workspace/no_tipping

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/misc/linux/rhel6/x86_64/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/misc/linux/rhel6/x86_64/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rjs454/workspace/no_tipping/CMakeFiles /home/rjs454/workspace/no_tipping/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rjs454/workspace/no_tipping/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libntg

# Build rule for target.
libntg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libntg
.PHONY : libntg

# fast build rule for target.
libntg/fast:
	$(MAKE) -f CMakeFiles/libntg.dir/build.make CMakeFiles/libntg.dir/build
.PHONY : libntg/fast

#=============================================================================
# Target rules for targets named ntg

# Build rule for target.
ntg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ntg
.PHONY : ntg

# fast build rule for target.
ntg/fast:
	$(MAKE) -f CMakeFiles/ntg.dir/build.make CMakeFiles/ntg.dir/build
.PHONY : ntg/fast

#=============================================================================
# Target rules for targets named ntgjni

# Build rule for target.
ntgjni: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ntgjni
.PHONY : ntgjni

# fast build rule for target.
ntgjni/fast:
	$(MAKE) -f CMakeFiles/ntgjni.dir/build.make CMakeFiles/ntgjni.dir/build
.PHONY : ntgjni/fast

combination.o: combination.cpp.o
.PHONY : combination.o

# target to build an object file
combination.cpp.o:
	$(MAKE) -f CMakeFiles/libntg.dir/build.make CMakeFiles/libntg.dir/combination.cpp.o
.PHONY : combination.cpp.o

combination.i: combination.cpp.i
.PHONY : combination.i

# target to preprocess a source file
combination.cpp.i:
	$(MAKE) -f CMakeFiles/libntg.dir/build.make CMakeFiles/libntg.dir/combination.cpp.i
.PHONY : combination.cpp.i

combination.s: combination.cpp.s
.PHONY : combination.s

# target to generate assembly for a file
combination.cpp.s:
	$(MAKE) -f CMakeFiles/libntg.dir/build.make CMakeFiles/libntg.dir/combination.cpp.s
.PHONY : combination.cpp.s

libntgjni.o: libntgjni.cpp.o
.PHONY : libntgjni.o

# target to build an object file
libntgjni.cpp.o:
	$(MAKE) -f CMakeFiles/ntgjni.dir/build.make CMakeFiles/ntgjni.dir/libntgjni.cpp.o
.PHONY : libntgjni.cpp.o

libntgjni.i: libntgjni.cpp.i
.PHONY : libntgjni.i

# target to preprocess a source file
libntgjni.cpp.i:
	$(MAKE) -f CMakeFiles/ntgjni.dir/build.make CMakeFiles/ntgjni.dir/libntgjni.cpp.i
.PHONY : libntgjni.cpp.i

libntgjni.s: libntgjni.cpp.s
.PHONY : libntgjni.s

# target to generate assembly for a file
libntgjni.cpp.s:
	$(MAKE) -f CMakeFiles/ntgjni.dir/build.make CMakeFiles/ntgjni.dir/libntgjni.cpp.s
.PHONY : libntgjni.cpp.s

ntg.o: ntg.cpp.o
.PHONY : ntg.o

# target to build an object file
ntg.cpp.o:
	$(MAKE) -f CMakeFiles/ntg.dir/build.make CMakeFiles/ntg.dir/ntg.cpp.o
.PHONY : ntg.cpp.o

ntg.i: ntg.cpp.i
.PHONY : ntg.i

# target to preprocess a source file
ntg.cpp.i:
	$(MAKE) -f CMakeFiles/ntg.dir/build.make CMakeFiles/ntg.dir/ntg.cpp.i
.PHONY : ntg.cpp.i

ntg.s: ntg.cpp.s
.PHONY : ntg.s

# target to generate assembly for a file
ntg.cpp.s:
	$(MAKE) -f CMakeFiles/ntg.dir/build.make CMakeFiles/ntg.dir/ntg.cpp.s
.PHONY : ntg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... libntg"
	@echo "... ntg"
	@echo "... ntgjni"
	@echo "... rebuild_cache"
	@echo "... combination.o"
	@echo "... combination.i"
	@echo "... combination.s"
	@echo "... libntgjni.o"
	@echo "... libntgjni.i"
	@echo "... libntgjni.s"
	@echo "... ntg.o"
	@echo "... ntg.i"
	@echo "... ntg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

