/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LibNtgJni */

#ifndef _Included_LibNtgJni
#define _Included_LibNtgJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LibNtgJni
 * Method:    setNumberOfWeights
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LibNtgJni_setNumberOfWeights
  (JNIEnv *, jobject, jint);

/*
 * Class:     LibNtgJni
 * Method:    Compute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibNtgJni_Compute
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
